services:
  postgres:
    image: postgres:15-alpine
    container_name: ecommerce-postgres
    environment:
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: ecommerce_user
      POSTGRES_PASSWORD: ecommerce_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - ecommerce-network

  redis:
    image: redis:7-alpine
    container_name: ecommerce-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - ecommerce-network

  app:
    build: .
    container_name: ecommerce-app
    environment:
      DATABASE_URL: 'postgresql://ecommerce_user:ecommerce_password@postgres:5432/ecommerce_db'
      JWT_SECRET: 'ecommerceappsupersecret'
      REDIS_HOST: 'redis'
      REDIS_PORT: '6379'
      NODE_ENV: 'production'
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis
    networks:
      - ecommerce-network
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma migrate deploy && npm run start:prod"

volumes:
  postgres_data:
  redis_data:

networks:
  ecommerce-network:
    driver: bridge
